databases:
  - name: ccsa-grupo-3-DB
    plan: free
    databaseName: ccsa-grupo-3-DB
    user: ccsa_grupo_3_db_user

services:
  - type: web
    plan: free
    name: ccsa-modulo-programacion-academica
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn ccsaProject.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ccsa-grupo-3-DB
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: ALLOWED_HOSTS 
        value: "ccsa-modulo-programacion-academica.onrender.com localhost"
      - key: DEBUG
        value: "True"
