# Generated by Django 5.0.3 on 2024-03-12 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postgraduateManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoSolicitud',
            fields=[
                ('codigo', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoContable',
            fields=[
                ('id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('fecha_reserva', models.DateField()),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fin', models.DateTimeField()),
                ('espacio_id_espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.espacio')),
                ('estadoSolicitud_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requestsManagement.estadosolicitud')),
                ('programa', models.ManyToManyField(to='postgraduateManagement.programa')),
                ('usuario_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contable',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('presupuesto', models.IntegerField()),
                ('cuenta_cobro', models.CharField(max_length=10)),
                ('docente_cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.docente')),
                ('programa', models.ManyToManyField(to='postgraduateManagement.programa')),
                ('usuario_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.usuario')),
                ('estadoSolicitud_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requestsManagement.estadosolicitud')),
                ('tipoContable_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requestsManagement.tipocontable')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
