# Generated by Django 5.0.4 on 2024-04-14 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('nrc', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('grupo', models.CharField(max_length=2)),
                ('cupo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id_espacio', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('id_subespacio', models.CharField(blank=True, default='00', max_length=2, null=True)),
                ('tipo', models.CharField(default='Salon', max_length=24)),
                ('capacidad', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoContrato',
            fields=[
                ('id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('codigo', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('semestre', models.CharField(max_length=2)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('codigo', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPrograma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('cedula', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('telefono', models.IntegerField()),
                ('url_foto', models.URLField()),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.ciudad')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('cedula', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('telefono', models.IntegerField()),
                ('url_foto', models.URLField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=8)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.ciudad')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocentesCursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.IntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.curso')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.docente')),
            ],
            options={
                'unique_together': {('docente', 'curso', 'prioridad')},
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='docente',
            field=models.ManyToManyField(through='postgraduateManagement.DocentesCursos', to='postgraduateManagement.docente'),
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('codigo', models.CharField(max_length=88, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('creditos', models.IntegerField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.departamento')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.materia'),
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(null=True)),
                ('fecha_fin', models.DateTimeField(null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.curso')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacio', to='postgraduateManagement.espacio')),
                ('espacio_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacio_asignado', to='postgraduateManagement.espacio')),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.modalidad')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.periodo'),
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('url_image', models.URLField()),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.director')),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.facultad')),
                ('tipo_de_programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.tipoprograma')),
            ],
        ),
        migrations.CreateModel(
            name='Pensum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.materia')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.periodo')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.programa')),
            ],
        ),
        migrations.AddField(
            model_name='materia',
            name='programas',
            field=models.ManyToManyField(through='postgraduateManagement.Pensum', to='postgraduateManagement.programa'),
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_elaboracion', models.DateField()),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.docente')),
                ('estado_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.estadocontrato')),
                ('tipo_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.tipocontrato')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.usuario'),
        ),
        migrations.AddConstraint(
            model_name='pensum',
            constraint=models.UniqueConstraint(fields=('materia', 'programa'), name='unique_materia_programa'),
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('grupo', 'materia')},
        ),
    ]
