# Generated by Django 5.0.3 on 2024-03-12 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('nrc', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('grupo', models.CharField(max_length=2)),
                ('cupo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id_espacio', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('id_subespacio', models.CharField(blank=True, default='00', max_length=2, null=True)),
                ('tipo', models.CharField(default='Salon', max_length=24)),
                ('capacidad', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoContrato',
            fields=[
                ('id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('codigo', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('semestre', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('codigo', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPrograma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('telefono', models.CharField(max_length=16)),
                ('cedula', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('contrato_codigo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.contrato')),
                ('cuidad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.cuidad')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pensum',
            fields=[
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('telefono', models.CharField(max_length=16)),
                ('cedula', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('contrato_codigo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.contrato')),
                ('cuidad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.cuidad')),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='docente_cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.docente'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='estadoContrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.estadocontrato'),
        ),
        migrations.CreateModel(
            name='DocentesCursos',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('creditos', models.IntegerField()),
                ('departamento_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('nrc', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('grupo', models.CharField(max_length=2)),
                ('cupo', models.IntegerField()),
                ('docente', models.ManyToManyField(to='postgraduateManagement.docente')),
                ('materia_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.materia')),
                ('usuario_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('codigo', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fin', models.DateTimeField()),
                ('curso_nrc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.curso')),
                ('espacio_id_espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.espacio')),
                ('modalidad_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.modalidad')),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('codigo', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('director_cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.director')),
                ('facultad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.facultad')),
                ('tipoPrograma_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.tipoprograma')),
            ],
        ),
        migrations.CreateModel(
            name='Pensum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.materia')),
                ('periodo_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.periodo')),
                ('programa_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.programa')),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipoContrato_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.tipocontrato'),
        ),
    ]
