# Generated by Django 5.0.3 on 2024-03-10 00:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('nrc', models.IntegerField(help_text='NRC del curso', primary_key=True, serialize=False)),
                ('grupo', models.IntegerField(help_text='numero del curso')),
                ('cupo', models.IntegerField(help_text='Cantidad de personas que tendrá el curso')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del departamento', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_curso', models.CharField(help_text='Código de la materia', max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre de la materia', max_length=120)),
                ('creditos', models.IntegerField(default=1, help_text='Cantidad de créditos que pesa la materia', validators=[django.core.validators.MinValueValidator(0, message='Los créditos deben ser al menos 0.'), django.core.validators.MaxValueValidator(20, message='Los créditos no pueden exceder 20.')])),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.IntegerField(help_text='Semestre académico', verbose_name=django.core.validators.MinValueValidator(0, message='El semestre debe ser mayor a 0.'))),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio del semestre')),
                ('fecha_fin', models.DateField(help_text='Fecha de finalización del semestre')),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.CharField(blank=True, choices=[('p', 'presencial'), ('v', 'virtual'), ('h', 'híbrida')], default='p', help_text='Modalidad de la clase', max_length=1)),
                ('fecha', models.DateField(help_text='Fecha de la clase')),
                ('hora_inicio', models.DateTimeField(help_text='Hora de inicio')),
                ('hora_fin', models.DateTimeField(help_text='Hora de finalización')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.curso')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.materia'),
        ),
    ]
