# Generated by Django 5.0.3 on 2024-03-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgraduateManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espacio',
            name='id_espacio',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
