# Generated by Django 4.2.11 on 2024-04-20 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postgraduateManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viatico',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('estado_viatico', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('finalizado', 'Finalizado')], default='Pendiente', max_length=15)),
                ('descripcion', models.TextField()),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('presupuesto', models.IntegerField()),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.curso')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgraduateManagement.docente')),
            ],
        ),
    ]
