# Generated by Django 4.2.11 on 2024-05-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgraduateManagement', '0002_alter_curso_cupo_alter_curso_grupo_alter_curso_nrc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='grupo',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nrc',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
