# Generated by Django 5.0.3 on 2024-03-17 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postgraduateManagement', '0002_profile'),
        ('postgraduateManagement', '0006_alter_espacio_id_subespacio'),
    ]

    operations = [
    ]
