# Generated by Django 5.0.2 on 2024-03-16 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postgraduateManagement', '0002_profile'),
        ('postgraduateManagement', '0006_alter_espacio_id_subespacio'),
    ]

    operations = [
    ]
