# Generated by Django 5.0.2 on 2024-03-16 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postgraduateManagement', '0007_merge_0002_profile_0006_alter_espacio_id_subespacio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
